services:
  backend:
    build: .
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=$NODE_ENV
      - API_PORT=$API_PORT
      - API_URL=$API_URL
      - DATABASE_URL=$DATABASE_URL
    command: ["node", "dist/server.js"]
