services:
  backend:
    build: .
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
      - API_PORT=$API_PORT
      - API_URL=$API_URL
      - DATABASE_URL=$DATABASE_URL
    depends_on:
      - db
    command: ["pnpm", "run", "dev"]

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - $POSTGRES_PORT
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
