name: deploy

on:
  push:
    branches:
      - qa
  pull_request:
    branches:
      - qa

env:
  COMMIT_HASH: ${{ github.sha }}
  REPO_NAME: ${{ github.repository }}
  API_PORT: $API_PORT
  API_URL: $API_URL
  DATABASE_URL: $DATABASE_URL
  NODE_ENV: $.NODE_ENV

jobs:
  build:
    runs-on: qa-fpx-server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          echo "Buildando a imagem..."
          export REPO_REF=$(echo $REPO_NAME | cut -d'/' -f2)
          export IMAGE=$REPO_REF:${COMMIT_HASH:0:8}
          echo "Realizando o build da imagem $IMAGE"
          docker build -t $IMAGE .
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV


  test:
    runs-on: qa-fpx-server
    needs: build
    steps:
      - name: Run tests
        run: |
          echo "Rodando os testes com Jest. Aguarde..."
          echo "Executando os testes na imagem $IMAGE"
          echo "Executando comando 'docker run --rm $IMAGE pnpm test'"
          docker run --rm $IMAGE pnpm test

          
  deploy:
    runs-on: qa-fpx-server
    needs: test
    steps:
      - name: Deploy application
        run: |
          echo "Efetuando deploy da aplicação..."
          echo "Imagem atual: $IMAGE"
          docker compose down --remove-orphans
          docker compose up -d
