name: qa-deploy

on:
  push:
    branches:
      - qa
  pull_request:
    branches:
      - qa

jobs:
  qa-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Checking workdir  
        run: echo "WORKDIR=$(pwd)" >> $GITHUB_ENV && $WORKDIR

      - name: Install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VM_HOST }} > ~/.ssh/known_hosts

      # - name: Connect with VM
      #   run: |
      #     ssh 
