name: deploy

on:
  push:
    branches:
      - qa
  pull_request:
    branches:
      - qa

env:
  COMMIT_HASH: ${{ github.sha }}
  REPO_NAME: ${{ github.repository }}
  API_PORT: ${{ secrets.API_PORT }}
  API_URL: ${{ secrets.API_URL }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  NODE_ENV: ${{ secrets.NODE_ENV }}

jobs:
  build:
    runs-on: qa-fpx-server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        id: build_image
        run: |
          echo "Buildando a imagem..."
          REPO_REF=$(echo $REPO_NAME | cut -d'/' -f2)
          IMAGE=$REPO_REF:${COMMIT_HASH:0:7}
          echo "Realizando o build da imagem $IMAGE"
          docker build -t $IMAGE .
          
          # Salvando a imagem em um arquivo
          echo $IMAGE > image.txt
          echo "Imagem salva em image.txt"

      - name: Upload image artifact
        uses: actions/upload-artifact@v3
        with:
          name: image
          path: image.txt  # Upload do arquivo contendo o valor da imagem

  test:
    runs-on: qa-fpx-server
    needs: build
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v3
        with:
          name: image

      - name: Run tests
        run: |
          IMAGE=$(cat image.txt)
          echo "Rodando os testes com Jest. Aguarde..."
          echo "Executando os testes na imagem $IMAGE"
          echo "Executando comando 'docker run --rm $IMAGE pnpm test'"
          docker run --rm $IMAGE pnpm test

  deploy:
    runs-on: qa-fpx-server
    needs: test
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v3
        with:
          name: image

      - name: Deploy application
        run: |
          IMAGE=$(cat image.txt)
          echo "Efetuando deploy da aplicação..."
          echo "Imagem atual: $IMAGE"
          docker compose down --remove-orphans
          docker compose up -d
