name: deploy

on:
  push:
    branches:
      - qa
  pull_request:
    branches:
      - qa

env:
  COMMIT_HASH: ${{ github.sha }}
  IMAGE: ${{ github.repository }}:${COMMIT_HASH:0:8}
  API_PORT: ${{ secrets.API_PORT }}
  API_URL: ${{ secrets.API_URL }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  NODE_ENV: ${{ secrets.NODE_ENV }}

jobs:
  build:
    runs-on: qa-fpx-server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          echo "IMAGE=${{ env.IMAGE }}"
          docker build -t ${{ env.IMAGE }} .    


  test:
    runs-on: qa-fpx-server
    needs: build
    steps:
      - name: Run tests
        run: |
          echo "Rodando os testes com Jest. Aguarde..."
          docker run --rm ${{ env.IMAGE }} pnpm test

          
  deploy:
    runs-on: qa-fpx-server
    needs: test
    steps:
      - name: Deploy application
        run: |
          echo "Efetuando deploy da aplicação..."
          echo "Imagem atual: ${{ env.IMAGE }}"
          docker compose down --remove-orphans
          docker compose up -d
