name: deploy

on:
  push:
    branches:
      - qa
  pull_request:
    branches:
      - qa

env:
  BRANCH_REF: ${{ github.ref_name }}
  COMMIT_HASH: ${{ github.sha }}
  REPO_NAME: ${{ github.repository }}
  API_PORT: ${{ secrets.API_PORT }}
  API_URL: ${{ secrets.API_URL }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  NODE_ENV: ${{ secrets.NODE_ENV }}

jobs:
  build:
    runs-on: qa-fpx-server
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Github References
        run: |
          echo ${{ github.action }}
          echo ${{ github.action_path }}
          echo ${{ github.action_ref }}
          echo ${{ github.action_repository }}
          echo ${{ github.action_status }}
          echo ${{ github.actor }}
          echo ${{ github.base_ref }}
          echo ${{ github.env }}
          echo ${{ github.event }}
          echo ${{ github.event_name }}
          echo ${{ github.event_path }}
          echo ${{ github.head_ref }}
          echo ${{ github.job }}
          echo ${{ github.job_workflow_sha }}
          echo ${{ github.path }}
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}
          echo ${{ github.ref_protected }}
          echo ${{ github.ref_type }}
          echo ${{ github.repository_owner }}
          echo ${{ github.workflow_ref }}
          echo ${{ github.workspace }}

      - name: Build Docker image
        id: build_image
        run: |
          echo "Buildando a imagem..."
          REPO_REF=$(echo $REPO_NAME | cut -d'/' -f2)
          IMAGE=$REPO_REF:${{ github.ref_name }}-${COMMIT_HASH:0:7}
          echo "Realizando o build da imagem $IMAGE"
          docker build -t $IMAGE .
          
          echo $IMAGE > image.txt
          echo "Imagem salva em image.txt"

      - name: Upload image artifact
        uses: actions/upload-artifact@v3
        with:
          name: image
          path: image.txt

  test:
    runs-on: qa-fpx-server
    needs: build
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v3
        with:
          name: image

      - name: Run tests
        run: |
          IMAGE=$(cat image.txt)
          echo "Rodando os testes com Jest. Aguarde..."
          echo "Executando os testes na imagem $IMAGE"
          docker run --rm $IMAGE pnpm test

  deploy:
    runs-on: qa-fpx-server
    needs: test
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v3
        with:
          name: image

      - name: Deploy application
        run: |
          export IMAGE=$(cat image.txt)
          echo "Efetuando deploy da aplicação..."
          echo "Imagem atual: $IMAGE"
          docker compose down --remove-orphans
          docker compose up -d
